# tools/scaffold_config.py
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import json, argparse, colorsys
from pathlib import Path


def hex_to_hls(hex_color: str):
    """Convert #rrggbb to (h, l, s) in range 0-1.
    Note: Python colorsys uses HLS order (Hue, Lightness, Saturation)."""
    h = hex_color.lstrip('#')
    r, g, b = (int(h[i:i+2], 16) / 255.0 for i in (0, 2, 4))
    return colorsys.rgb_to_hls(r, g, b)   # returns (H, L, S)


def _hls_to_hex(h, l, s) -> str:
    r, g, b = colorsys.hls_to_rgb(h, l, s)
    return '#{:02x}{:02x}{:02x}'.format(round(r * 255), round(g * 255), round(b * 255))


def derive_brand_colors(primary_hex: str, secondary_hex: str) -> dict:
    h, l, s = hex_to_hls(primary_hex)

    def swatch(delta):
        return _hls_to_hex(h, min(0.9, l + delta), s)

    # Navy palette
    navy      = primary_hex
    navy_mid   = swatch(0.10)
    navy_soft  = swatch(0.25)
    navy_pale  = swatch(0.38)
    navy_ghost = swatch(0.55)

    # navyRgb
    nr, ng, nb = colorsys.hls_to_rgb(h, l, s)
    navy_rgb = f"{round(nr*255)},{round(ng*255)},{round(nb*255)}"

    # Accent palette
    ha, la, sa = hex_to_hls(secondary_hex)
    accent_light = _hls_to_hex(ha, 0.95, sa)
    ar, ag, ab   = colorsys.hls_to_rgb(ha, la, sa)
    accent_soft  = f"rgba({round(ar*255)},{round(ag*255)},{round(ab*255)},0.55)"

    return {
        'navy':        navy,
        'navyMid':     navy_mid,
        'navySoft':    navy_soft,
        'navyPale':    navy_pale,
        'navyGhost':   navy_ghost,
        'navyRgb':     navy_rgb,
        'accent':      secondary_hex,
        'accentLight': accent_light,
        'accentSoft':  accent_soft,
        'accentRed':   '#D85F52',
    }


def scaffold_config(venue: dict) -> str:
    t  = venue['team']
    id_ = venue['identity']
    v  = venue['venue']
    svg = venue['svg']

    brand = derive_brand_colors(id_['primary_hex'], id_['secondary_hex'])

    # sections = zone names in layer order
    zones = sorted(svg['zones'], key=lambda z: z['layer'])
    sections = [z['data_zone'] for z in zones]
    section_weights = [100] * len(sections)
    gates = [g['data_gate'] for g in svg['gates']]

    weights = svg.get('gate_by_zone_weights', {})
    weights_js = '{\n'
    # Sort by zone layer order for deterministic output
    for name, arr in sorted(weights.items(), key=lambda x: sections.index(x[0]) if x[0] in sections else 999):
        weights_js += f"    '{name}': {arr},\n"
    weights_js += '  }'

    sections_js = json.dumps(sections)
    gates_js    = json.dumps(gates)

    return f"""\
// AUTO-GENERATED by scaffold_config.py — review all fields before use
// Source: {t['slug']}-venue.json
// Fill in all STUB_ values before running node build.js

// ── TEAM IDENTITY ──────────────────────────────
const TEAM = {{
  sport:           '{venue["sport"]}',
  orgName:         '{t["name"]}',
  shortName:       '{t["short_name"]}',
  logoFile:        'STUB_LOGO_FILE.png',
  stmLabel:        '{t["stm_label"]}',
  ticketingVendor: '{id_["ticketing_vendor"]}',
  scanVendor:      '{id_["scan_vendor"]}',
  fnbVendor:       '{id_["fnb_vendor"]}',
}};

// ── BRAND ──────────────────────────────────────
const BRAND = {{
  navy:        '{brand["navy"]}',
  navyMid:     '{brand["navyMid"]}',
  navySoft:    '{brand["navySoft"]}',
  navyPale:    '{brand["navyPale"]}',
  navyGhost:   '{brand["navyGhost"]}',
  accent:      '{brand["accent"]}',
  accentLight: '{brand["accentLight"]}',
  accentSoft:  '{brand["accentSoft"]}',
  accentRed:   '{brand["accentRed"]}',
  navyRgb:     '{brand["navyRgb"]}',
}};

// ── VENUE ──────────────────────────────────────
const VENUE = {{
  name:     '{v["name"]}',
  capacity: {v["capacity"]},
  sections: {sections_js},
  sectionWeights: {section_weights},
  gates:    {gates_js},
  gateBySectionWeights: {weights_js},
}};

// ── UPCOMING PACING ─── STUB: replace with current season data ──
const UPCOMING_PACING = [];

// ── SCHEDULE ─── STUB: replace with current season schedule ────
const SERIES_SCHEDULE = [];

// ── FAN GEOGRAPHY ─── STUB: replace with fan base data ─────────
const HOME_STATES   = ['STUB_STATE'];
const STATE_WEIGHTS = [100];

if (typeof module !== 'undefined') {{
  module.exports = {{ TEAM, BRAND, VENUE, UPCOMING_PACING, SERIES_SCHEDULE, HOME_STATES, STATE_WEIGHTS }};
}}
"""


def main():
    parser = argparse.ArgumentParser(description='Scaffold client-config.js from venue JSON')
    parser.add_argument('venue_json', help='Path to [slug]-venue.json')
    parser.add_argument('--dry-run', action='store_true',
                        help='Print output to stdout without writing file')
    args = parser.parse_args()

    venue_path = Path(args.venue_json)
    if not venue_path.exists():
        print(f"ERROR: {venue_path} not found", file=sys.stderr)
        sys.exit(1)

    venue = json.loads(venue_path.read_text())
    slug  = venue['team']['slug']
    output = scaffold_config(venue)

    if args.dry_run:
        print(output)
        sys.exit(0)

    out_path = venue_path.parent / f"{slug}-config-stub.js"
    out_path.write_text(output)
    print(f"Written: {out_path}")
    print(f"  Copy to src/client-config.js and fill in all STUB_ values")
    print(json.dumps({"status": "ok", "config_stub": str(out_path), "slug": slug}))


if __name__ == '__main__':
    main()
