// AUTO-GENERATED by scaffold_config.py — review all fields before use
// Source: chicago-cubs-venue.json
// Fill in all STUB_ values before running node build.js

// ── TEAM IDENTITY ──────────────────────────────
const TEAM = {
  sport:           'mlb',
  orgName:         'Chicago Cubs',
  shortName:       'Cubs',
  logoFile:        'STUB_LOGO_FILE.png',
  stmLabel:        'Cubs Season Ticket Holder',
  ticketingVendor: 'SeatGeek',
  scanVendor:      'MLB Ballpark App',
  fnbVendor:       'Levy Restaurants',
};

// ── BRAND ──────────────────────────────────────
const BRAND = {
  navy:        '#0E3386',
  navyMid:     '#1345b4',
  navySoft:    '#2b65e9',
  navyPale:    '#6791ef',
  navyGhost:   '#b5caf7',
  accent:      '#CC3433',
  accentLight: '#faebeb',
  accentSoft:  'rgba(204,52,51,0.55)',
  accentRed:   '#D85F52',
  navyRgb:     '14,51,134',
};

// ── VENUE ──────────────────────────────────────
const VENUE = {
  name:     'Wrigley Field',
  capacity: 41649,
  sections: ["Upper Box", "Upper Reserved", "Terrace Box", "Budweiser Bleachers", "Standing Room Only", "Field Box", "Club Box", "Premium Club / 1914 Club"],
  sectionWeights: [100, 100, 100, 100, 100, 100, 100, 100],
  gates:    ["Marquee Gate", "Gallagher Way Gate", "CD Peacock Premier Entrance", "Left Field Gate", "Budweiser Bleacher Gate", "Wintrust Right Field Gate"],
  gateBySectionWeights: {
    'Upper Box': [3, 4, 2, 3, 2, 3],
    'Upper Reserved': [3, 3, 2, 3, 2, 3],
    'Terrace Box': [4, 4, 3, 2, 2, 3],
    'Budweiser Bleachers': [1, 1, 1, 5, 8, 2],
    'Standing Room Only': [3, 3, 2, 2, 2, 3],
    'Field Box': [4, 3, 2, 1, 1, 4],
    'Club Box': [5, 3, 4, 1, 1, 2],
    'Premium Club / 1914 Club': [2, 1, 8, 1, 1, 1],
  },
};

// ── UPCOMING PACING ─── STUB: replace with current season data ──
const UPCOMING_PACING = [
  {
    "opponent": "St. Louis Cardinals",
    "date": "2026-05-06",
    "daysUntil": 1,
    "pctSold": 82
  },
  {
    "opponent": "St. Louis Cardinals",
    "date": "2026-05-07",
    "daysUntil": 2,
    "pctSold": 85
  },
  {
    "opponent": "St. Louis Cardinals",
    "date": "2026-05-08",
    "daysUntil": 3,
    "pctSold": 88
  },
  {
    "opponent": "Cincinnati Reds",
    "date": "2026-05-09",
    "daysUntil": 4,
    "pctSold": 71
  },
  {
    "opponent": "Cincinnati Reds",
    "date": "2026-05-10",
    "daysUntil": 5,
    "pctSold": 69
  },
  {
    "opponent": "Cincinnati Reds",
    "date": "2026-05-11",
    "daysUntil": 6,
    "pctSold": 67
  },
  {
    "opponent": "Atlanta Braves",
    "date": "2026-05-12",
    "daysUntil": 7,
    "pctSold": 74
  },
  {
    "opponent": "Atlanta Braves",
    "date": "2026-05-13",
    "daysUntil": 8,
    "pctSold": 76
  },
  {
    "opponent": "Atlanta Braves",
    "date": "2026-05-14",
    "daysUntil": 9,
    "pctSold": 73
  },
  {
    "opponent": "Milwaukee Brewers",
    "date": "2026-05-15",
    "daysUntil": 10,
    "pctSold": 80
  },
  {
    "opponent": "Milwaukee Brewers",
    "date": "2026-05-16",
    "daysUntil": 11,
    "pctSold": 83
  },
  {
    "opponent": "Milwaukee Brewers",
    "date": "2026-05-17",
    "daysUntil": 12,
    "pctSold": 79
  },
  {
    "opponent": "San Francisco Giants",
    "date": "2026-05-18",
    "daysUntil": 13,
    "pctSold": 68
  },
  {
    "opponent": "San Francisco Giants",
    "date": "2026-05-19",
    "daysUntil": 14,
    "pctSold": 66
  }
];

// ── SCHEDULE ─── STUB: replace with current season schedule ────
const SERIES_SCHEDULE = [
  {
    "start": "2026-03-26",
    "opp": "Milwaukee Brewers",
    "lg": "NL",
    "rival": true,
    "n": 3,
    "tier": "featured",
    "promo": "giveaway",
    "promoLabel": "Opening Day Bobblehead"
  },
  {
    "start": "2026-03-30",
    "opp": "Pittsburgh Pirates",
    "lg": "NL",
    "rival": false,
    "n": 3,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-04-06",
    "opp": "San Diego Padres",
    "lg": "NL",
    "rival": false,
    "n": 3,
    "tier": "select",
    "promo": "theme_night",
    "promoLabel": "Taco Tuesday Night"
  },
  {
    "start": "2026-04-10",
    "opp": "Colorado Rockies",
    "lg": "NL",
    "rival": false,
    "n": 3,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-04-13",
    "opp": "St. Louis Cardinals",
    "lg": "NL",
    "rival": true,
    "n": 4,
    "tier": "featured",
    "promo": "giveaway",
    "promoLabel": "Cardinals Rivalry Jersey"
  },
  {
    "start": "2026-04-17",
    "opp": "Miami Marlins",
    "lg": "NL",
    "rival": false,
    "n": 3,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-04-21",
    "opp": "Washington Nationals",
    "lg": "NL",
    "rival": false,
    "n": 3,
    "tier": "standard",
    "promo": "theme_night",
    "promoLabel": "Earth Day Green Night"
  },
  {
    "start": "2026-04-24",
    "opp": "New York Mets",
    "lg": "NL",
    "rival": false,
    "n": 3,
    "tier": "select",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-04-28",
    "opp": "Cincinnati Reds",
    "lg": "NL",
    "rival": false,
    "n": 3,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-05-06",
    "opp": "St. Louis Cardinals",
    "lg": "NL",
    "rival": true,
    "n": 3,
    "tier": "featured",
    "promo": "giveaway",
    "promoLabel": "Cubs Legend Bobblehead"
  },
  {
    "start": "2026-05-09",
    "opp": "Cincinnati Reds",
    "lg": "NL",
    "rival": false,
    "n": 3,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-05-12",
    "opp": "Atlanta Braves",
    "lg": "NL",
    "rival": false,
    "n": 3,
    "tier": "select",
    "promo": "theme_night",
    "promoLabel": "Star Wars Night"
  },
  {
    "start": "2026-05-15",
    "opp": "Milwaukee Brewers",
    "lg": "NL",
    "rival": true,
    "n": 3,
    "tier": "featured",
    "promo": "giveaway",
    "promoLabel": "Ernie Banks T-Shirt"
  },
  {
    "start": "2026-05-18",
    "opp": "San Francisco Giants",
    "lg": "NL",
    "rival": false,
    "n": 2,
    "tier": "select",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-05-22",
    "opp": "Philadelphia Phillies",
    "lg": "NL",
    "rival": false,
    "n": 3,
    "tier": "select",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-05-25",
    "opp": "Kansas City Royals",
    "lg": "AL",
    "rival": false,
    "n": 3,
    "tier": "standard",
    "promo": "theme_night",
    "promoLabel": "Memorial Day Military Night"
  },
  {
    "start": "2026-05-29",
    "opp": "Arizona Diamondbacks",
    "lg": "NL",
    "rival": false,
    "n": 3,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-06-01",
    "opp": "Pittsburgh Pirates",
    "lg": "NL",
    "rival": false,
    "n": 3,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-06-05",
    "opp": "Los Angeles Dodgers",
    "lg": "NL",
    "rival": false,
    "n": 3,
    "tier": "featured",
    "promo": "giveaway",
    "promoLabel": "Cubs Hat Giveaway"
  },
  {
    "start": "2026-06-09",
    "opp": "Detroit Tigers",
    "lg": "AL",
    "rival": false,
    "n": 3,
    "tier": "standard",
    "promo": "theme_night",
    "promoLabel": "Pride Night"
  },
  {
    "start": "2026-06-12",
    "opp": "St. Louis Cardinals",
    "lg": "NL",
    "rival": true,
    "n": 4,
    "tier": "featured",
    "promo": "giveaway",
    "promoLabel": "Ryne Sandberg Bobblehead"
  },
  {
    "start": "2026-06-19",
    "opp": "Houston Astros",
    "lg": "AL",
    "rival": false,
    "n": 3,
    "tier": "select",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-06-23",
    "opp": "Colorado Rockies",
    "lg": "NL",
    "rival": false,
    "n": 3,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-06-26",
    "opp": "Milwaukee Brewers",
    "lg": "NL",
    "rival": true,
    "n": 3,
    "tier": "featured",
    "promo": "theme_night",
    "promoLabel": "Fireworks Friday"
  },
  {
    "start": "2026-06-30",
    "opp": "New York Yankees",
    "lg": "AL",
    "rival": false,
    "n": 3,
    "tier": "featured",
    "promo": "giveaway",
    "promoLabel": "Cubs Replica Jersey"
  },
  {
    "start": "2026-07-03",
    "opp": "Miami Marlins",
    "lg": "NL",
    "rival": false,
    "n": 3,
    "tier": "standard",
    "promo": "theme_night",
    "promoLabel": "Independence Day Fireworks"
  },
  {
    "start": "2026-07-09",
    "opp": "Washington Nationals",
    "lg": "NL",
    "rival": false,
    "n": 2,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  }
];

// ── FAN GEOGRAPHY ─── STUB: replace with fan base data ─────────
const HOME_STATES = ["IL","WI","IN","MO","IA","MI","OH","MN","FL","CA"];
const STATE_WEIGHTS = [500,120,90,75,60,50,40,35,25,20];

if (typeof module !== 'undefined') {
  module.exports = { TEAM, BRAND, VENUE, UPCOMING_PACING, SERIES_SCHEDULE, HOME_STATES, STATE_WEIGHTS };
}
